Repository Dragon-Pyramid/gym-master, pull requests merged in 2025-07, with the labels that each got.

#17 feat: Añadir filtros de estado (Todos/Activos/Inactivos) a las tablas con campo 'activo'
  src/app/dashboard/cuotas/page.tsx
  src/app/dashboard/servicios/page.tsx
  src/app/dashboard/socios/page.tsx
  src/app/dashboard/usuarios/page.tsx
  src/components/tables/CuotaTable.tsx
Labels: enhancement

#29 Mejora integral de soporte para modo oscuro en todos los modales de vista
  package-lock.json
  src/app/dashboard/avisos/page.tsx
  src/app/dashboard/pagos/page.tsx
  src/components/forms/AvisosForm.tsx
  src/components/modal/ActividadViewModal.tsx
  src/components/modal/AsistenciaViewModal.tsx
  src/components/modal/AvisosModalView.tsx
  src/components/modal/CuotasViewModal.tsx
  src/components/modal/OtrosGastosViewModal.tsx
  src/components/modal/PagoViewModal.tsx
  src/components/modal/ProductoViewModal.tsx
  src/components/modal/ProveedorViewModal.tsx
  src/components/modal/RutinaModalView.tsx
  src/components/modal/ServicioViewModal.tsx
  src/components/modal/SocioViewModal.tsx
  src/components/modal/UserViewModal.tsx
  src/components/modal/VentaDetalleViewModal.tsx
  src/components/modal/VentaViewModal.tsx
  src/components/tables/AvisosTable.tsx
  src/components/ui/TextEditor.tsx
Labels: bug, enhancement

#43 Refactor global: Autenticación persistente, servicios centralizados y soporte QR seguro
  package-lock.json
  package.json
  src/app/auth/login/page.tsx
  src/app/dashboard/actividades/page.tsx
  src/app/dashboard/admin/page.tsx
  src/app/dashboard/asistencias/page.tsx
  src/app/dashboard/avisos/page.tsx
  src/app/dashboard/control-asistencia/page.tsx
  src/app/dashboard/cuotas/page.tsx
  src/app/dashboard/dietas/page.tsx
  src/app/dashboard/equipamientos/page.tsx
  src/app/dashboard/otros-gastos/page.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/pagos/page.tsx
  src/app/dashboard/productos/page.tsx
  src/app/dashboard/proveedores/page.tsx
  src/app/dashboard/rutinas/page.tsx
  src/app/dashboard/servicios/page.tsx
  src/app/dashboard/socios/page.tsx
  src/app/dashboard/usuarios/page.tsx
  src/app/dashboard/ventas-detalle/page.tsx
  src/app/dashboard/ventas/page.tsx
  src/components/header/AppHeader.tsx
  src/components/sidebar/AppSidebar.tsx
  src/components/sidebar/sidebarConfig.ts
  src/components/ui/RegistrarAsistenciaQR.tsx
  src/components/ui/gym-selector.tsx
  src/components/ui/qr-display.tsx
  src/config/gymOptions.ts
  src/hooks/useSidebarSection.ts
  src/services/apiClient.ts
  src/services/loginService.ts
  src/services/qrService.ts
  src/services/storageService.ts
  src/services/supabaseClient.ts
  src/stores/authStore.ts
Labels: Error, Mejora

#53 Mejoras en Dashboard Metricas y Agregado de Swagger UI para avance de documentación
  package-lock.json
  package.json
  src/app/api/admin/metricas/asistencia/[tipo]/route.ts
  src/app/api/admin/metricas/rutinas/adherencia/route.ts
  src/app/dashboard/page.tsx
  src/app/swagger/page.tsx
  src/middlewares/rolAdmin.middleware.ts
  src/services/apiClient.ts
Labels: Mejora, Consulta
